name: mdse
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=1.12.1
  - torchvision=0.13.0
  - numpy
  - opencv
  - matplotlib
  - scikit-learn
  - pillow
  - scipy
  - h5py
  - pip
  - pip:
    - spikingjelly>=0.0.0.0.12
    - timm>=0.5.0
    - tqdm>=4.60.0
    - tensorboard>=2.8.0
    - ml-collections>=0.1.0
    - ebdataset>=0.1.0
